# Generated by Django 4.0.2 on 2022-02-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('company_email', models.EmailField(max_length=36)),
                ('password', models.CharField(max_length=36)),
                ('contact_number', models.IntegerField(max_length=15)),
                ('organisation_logo', models.ImageField(upload_to='images/')),
                ('industry', models.CharField(max_length=36)),
                ('company_display_name', models.CharField(max_length=36)),
                ('company_description', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('company_country', models.CharField(max_length=36)),
                ('company_city', models.CharField(max_length=36)),
                ('company_website', models.URLField(max_length=250)),
            ],
        ),
    ]
