# Generated by Django 4.0.2 on 2022-02-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('company_email', models.EmailField(max_length=36)),
                ('password', models.CharField(max_length=36)),
                ('contact_number', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='images/')),
                ('industry', models.CharField(max_length=36)),
                ('display_name', models.CharField(max_length=36)),
                ('description', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=36)),
                ('city', models.CharField(max_length=36)),
                ('website', models.URLField(max_length=250)),
            ],
        ),
    ]
