# Generated by Django 4.0.2 on 2022-02-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='company_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='company_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='company_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='company_display_name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='organisation_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='company_website',
            new_name='website',
        ),
    ]
