# Generated by Django 4.0.2 on 2022-02-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_rename_company_city_organisation_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='slug',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
