# Generated by Django 4.0.2 on 2022-02-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_remove_organisation_logo_remove_organisation_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
