# Generated by Django 4.0.2 on 2022-02-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0005_alter_organisation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
