# Generated by Django 4.0.2 on 2022-02-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_alter_organisation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='company_email',
            field=models.EmailField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=36),
        ),
    ]
