# Generated by Django 4.0.2 on 2022-02-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_alter_organisation_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='company_email',
            field=models.EmailField(max_length=36),
        ),
    ]
