# Generated by Django 4.0.2 on 2022-02-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_alter_organisation_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
