# Generated by Django 4.0.2 on 2022-02-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0016_alter_organisation_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='slug',
        ),
    ]
